import { Montserrat } from 'next/font/google';

import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';

import type { Metadata } from 'next';
import { Sprite } from '@/core/ui/Icon/Sprite';

import './globals.css';

const montserratFont = Montserrat({
    weight: ['700', '600', '500', '400'],
    subsets: ['cyrillic', 'latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${montserratFont.className}`}>
                <Sprite/>
                <Header/>
                <main>
                    {children}
                </main>
                <Footer/>
            </body>
        </html>
    );
}
